### PR TITLE
Optional Settings: Provide 2x/3x Images for Retina support

### PR DESCRIPTION
**Pull request by pc-coholic**
If you ever woke up and said to yourself: "I really, really, really, REALLY want a super cluttered settings-screen and upload three pictures in three different dimensions".

If that person is you, this PR will make your wildest dreams come true :tada:

### CODE REVIEW

**Comment by rixx** [comment]
I know file uploads are ugly no matter what, but you could consider arranging them in some sort of table, to provide help and structure to those few of us who do not prefer super cluttered settings. :wink:

**Comment by pc-coholic** [comment]
Please correct me if I'm wrong - but with the provided `settings_form_fields` and `settings_content_render`, I am not able to override the layout of the settings-fields?

The usage of `'data-display-dependency': '#id_ticketoutput_passbook_selfscale'` at least hides the 6 extra fields unless a user specifically requests them to be enabled - so for the majority of users, the display screen pretty much won't change at all...

**Comment by rixx** [comment]
Ah, yeah, sorry, I was thinking about ye olde days when plugin settings would've been an HTML insert. Don't mind me.

**Comment by raphaelm** [comment]
I think this is great, only suggestion: Can we generate the help_text values with the resolutions in a way that doesn't force our translators to translate the same sentence 9 times?

**Comment by pc-coholic** [comment]
I simplified the translations as requested... Also now respecting the selfscale-boolean if it has been turned off, but there are still uploaded graphics present.

**Comment by raphaelm** [comment]
Thansk a lot!

**Pull request merged**
